<?php

namespace WPBakeryDivi5Converter\Tests;

use PHPUnit\Framework\TestCase;
use WPBakeryDivi5Converter\Helpers\IconMap;

/**
 * data/fa-icons.json is generated by scripts/build-fa-icon-map.php from Divi
 * 5.12.1's own icon-library/src/components/icon-font/iconList.json
 * (references/Divi.zip). The unicode/weight values asserted below were read
 * from that same file: `adjust` (styles solid+fa, weight 900), `envelope`
 * (styles line+fa, weight 400), `facebook-f` (styles solid+fa, weight 400).
 */
final class IconMapTest extends TestCase {

    public function test_fa5_and_fa6_solid_prefixes_agree(): void {
        $fa5 = IconMap::fromClass( 'fas fa-adjust' );
        $fa6 = IconMap::fromClass( 'fa-solid fa-adjust' );

        $this->assertSame( $fa5, $fa6 );
        $this->assertTrue( $fa5['exact'] );
        $this->assertSame( [ 'unicode' => '&#xf042;', 'type' => 'fa', 'weight' => '900' ], $fa5['icon'] );
        $this->assertSame( 'adjust', $fa5['name'] );
    }

    public function test_far_regular_prefix_is_weight_400(): void {
        $result = IconMap::fromClass( 'far fa-envelope' );

        $this->assertTrue( $result['exact'] );
        $this->assertSame( [ 'unicode' => '&#xf0e0;', 'type' => 'fa', 'weight' => '400' ], $result['icon'] );
    }

    public function test_fab_brands_prefix_is_weight_400(): void {
        $result = IconMap::fromClass( 'fab fa-facebook-f' );

        $this->assertTrue( $result['exact'] );
        $this->assertSame( [ 'unicode' => '&#xf39e;', 'type' => 'fa', 'weight' => '400' ], $result['icon'] );
    }

    public function test_fa6_regular_and_brands_family_classes_are_recognised(): void {
        $regular = IconMap::fromClass( 'fa-regular fa-envelope' );
        $brands  = IconMap::fromClass( 'fa-brands fa-facebook-f' );

        $this->assertSame( '400', $regular['icon']['weight'] );
        $this->assertSame( '400', $brands['icon']['weight'] );
    }

    public function test_a_non_font_awesome_class_falls_back_to_the_star(): void {
        $result = IconMap::fromClass( 'vc-oi vc-oi-dial' );

        $this->assertFalse( $result['exact'] );
        $this->assertSame( IconMap::FALLBACK, $result['icon'] );
        $this->assertSame( 'vc-oi vc-oi-dial', $result['name'] );
    }

    public function test_an_unknown_fa_name_falls_back_to_the_star(): void {
        $result = IconMap::fromClass( 'fas fa-totally-not-a-real-icon' );

        $this->assertFalse( $result['exact'] );
        $this->assertSame( IconMap::FALLBACK, $result['icon'] );
        $this->assertSame( 'totally-not-a-real-icon', $result['name'] );
    }

    public function test_empty_class_falls_back_to_the_star(): void {
        $result = IconMap::fromClass( '' );

        $this->assertFalse( $result['exact'] );
        $this->assertSame( IconMap::FALLBACK, $result['icon'] );
        $this->assertSame( '', $result['name'] );
    }

    public function test_is_font_awesome(): void {
        $this->assertTrue( IconMap::isFontAwesome( 'fas fa-adjust' ) );
        $this->assertTrue( IconMap::isFontAwesome( 'fa-solid fa-adjust' ) );
        $this->assertFalse( IconMap::isFontAwesome( 'vc-oi vc-oi-dial' ) );
    }
}
